name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release NuGet Package
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src/WouterVanRanst.Utils

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Build NuGet Package
      run: dotnet pack --configuration Release /p:Version=${{ steps.get_version.outputs.VERSION }}

    - name: Publish NuGet Package
      run: dotnet nuget push bin/Release/WouterVanRanst.Utils.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate



    
